### ISSUE TITLE
Release 4.7.3 [Current 4.7.2 has build failure with ghc 8.10.3]

### ISSUE THREAD

**Issue by andreasabel** [ddssff/listlike#8]
ListLike does not build with the latest ghc, probably because of the new version of `bytestring` shipped with that ghc.
```
$ cabal v1-install ListLike
Resolving dependencies...
Configuring ListLike-4.7.2...
...
[20 of 21] Compiling Data.ListLike.Instances ( src/Data/ListLike/Instances.hs, dist/build/Data/ListLike/Instances.o, dist/build/Data/ListLike/Instances.dyn_o )

src/Data/ListLike/Instances.hs:135:10: error:
    Duplicate instance declarations:
      instance IsList BSC.ByteString
        -- Defined at src/Data/ListLike/Instances.hs:135:10
      instance IsList BSC.ByteString
        -- Defined in ‘Data.ByteString.Internal’
    |
135 | instance IsList BS.ByteString where
    |          ^^^^^^^^^^^^^^^^^^^^

src/Data/ListLike/Instances.hs:258:10: error:
    Duplicate instance declarations:
      instance IsList BSLC.ByteString
        -- Defined at src/Data/ListLike/Instances.hs:258:10
      instance IsList BSLC.ByteString
        -- Defined in ‘Data.ByteString.Lazy.Internal’
    |
258 | instance IsList BSL.ByteString where
    |          ^^^^^^^^^^^^^^^^^^^^^
Failed to install ListLike-4.7.2


$ ghc --version
The Glorious Glasgow Haskell Compilation System, version 8.10.3

$ ghc-pkg list | grep byte
    bytestring-0.10.12.0
```

**Comment by asr** [comment]
The current master (c6ef5ceca4fe94c002213f463ecb2f42f3572c58) builds with GHC 8.10.3. Please release a new version to Hackage.

Blocking https://github.com/agda/agda/issues/5109.

**Comment by fishtreesugar** [comment]
I met the same issue (Homebrew/homebrew-core#67284) when I tried to build `futhark-0.18.4` on ghc-8.10.3, which `ListLike-4.7.2` is a transitive dependency via `process-extras-0.7.4`:
```
src/Data/ListLike/Instances.hs:135:10: error:
    Duplicate instance declarations:
      instance IsList BSC.ByteString
        -- Defined at src/Data/ListLike/Instances.hs:135:10
      instance IsList BSC.ByteString
        -- Defined in ‘Data.ByteString.Internal’
    |
135 | instance IsList BS.ByteString where
    |          ^^^^^^^^^^^^^^^^^^^^

src/Data/ListLike/Instances.hs:258:10: error:
    Duplicate instance declarations:
      instance IsList BSLC.ByteString
        -- Defined at src/Data/ListLike/Instances.hs:258:10
      instance IsList BSLC.ByteString
        -- Defined in ‘Data.ByteString.Lazy.Internal’
    |
258 | instance IsList BSL.ByteString where
    |          ^^^^^^^^^^^^^^^^^^^^^
cabal: Failed to build ListLike-4.7.2 (which is required by exe:futhark from
futhark-0.18.4). See the build log above for details.
```

And I think this issue is already fixed in #7, but the new version has not yet bump to hackage. We can tighten up the upper bound of bytestring as `0.10.10.1` to workaround this issue.

**Comment by andreasabel** [comment]
The OP is already fixed by 436ba4fc40d7530a86c93307e92115e6381722e7, I guess it only takes a release...

**Comment by andreasabel** [comment]
See PR #9.

**Comment by arrowd** [comment]
FreeBSD port of hoogle also blocked by this.

**Comment by ddssff** [comment]
Looks like there still an issue #10

**Comment by newhoggy** [comment]
I've tested https://github.com/ddssff/listlike/pull/9 in a large project and it works well.  Keen for a release.

**Comment by andreasabel** [comment]
4.7.3 has already been released https://hackage.haskell.org/package/ListLike-4.7.3 (2020-12-31).
We need to release 4.7.4 [#12].
