### ISSUE TITLE
Release 4.7.4 

### ISSUE THREAD

**Issue by L-TChen** [ddssff/listlike#12]
Original title: ListLike 4.7.3 build failure with ghc 8.8.4

The latest version 4.7.3 (after the fix for GHC 8.10.3) unfortunately fails to build with ghc 8.8.4 and 8.10.2.
```
[13 of 21] Compiling Data.ListLike.UTF8 ( src/Data/ListLike/UTF8.hs, dist/build/Data/ListLike/UTF8.o )

src/Data/ListLike/UTF8.hs:153:10: error:
    • Overlapping instances for IsString (UTF8 BSC.ByteString)
        arising from the superclasses of an instance declaration
      Matching instances:
        instance UTF8.UTF8Bytes string index => IsString (UTF8 string)
          -- Defined in ‘Data.String.UTF8’
        instance IsString (UTF8 BSC.ByteString)
          -- Defined at src/Data/ListLike/UTF8.hs:150:10
    • In the instance declaration for
        ‘StringLike (UTF8 BSC.ByteString)’
    |
153 | instance StringLike (UTF8 BS.ByteString) where
    |          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

src/Data/ListLike/UTF8.hs:277:10: error:
    • Overlapping instances for IsString (UTF8 BSLC.ByteString)
        arising from the superclasses of an instance declaration
      Matching instances:
        instance UTF8.UTF8Bytes string index => IsString (UTF8 string)
          -- Defined in ‘Data.String.UTF8’
        instance IsString (UTF8 BSLC.ByteString)
          -- Defined at src/Data/ListLike/UTF8.hs:274:10
    • In the instance declaration for
        ‘StringLike (UTF8 BSLC.ByteString)’
    |
277 | instance StringLike (UTF8 BSL.ByteString) where
    |          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
cabal: Failed to build ListLike-4.7.3 (which is required by
tasty-silver-3.1.15). See the build log above for details.

~$ ghc-pkg list | grep byte
    bytestring-0.10.10.1
```

**Comment by L-TChen** [comment]
It seems that `utf8-string-1.0.2` conflicts with `ListLike`. Restricting to `utf8-string-1.0.1.1` works again. 
```
~/.cabal$ cabal install --lib utf8-string-1.0.1.1 ListLike-4.7.3
Resolving dependencies...
Build profile: -w ghc-8.8.4 -O1
In order, the following will be built (use -v for more details):
 - primitive-0.7.1.0 (lib) (requires build)
 - utf8-string-1.0.1.1 (lib:utf8-string) (requires build)
 - vector-0.12.1.2 (lib) (requires build)
 - ListLike-4.7.3 (lib) (requires build)
Starting     utf8-string-1.0.1.1 (all, legacy fallback)
Starting     primitive-0.7.1.0 (lib)
Building     utf8-string-1.0.1.1 (all, legacy fallback)
Building     primitive-0.7.1.0 (lib)
Installing   utf8-string-1.0.1.1 (all, legacy fallback)
Completed    utf8-string-1.0.1.1 (all, legacy fallback)
Installing   primitive-0.7.1.0 (lib)
Completed    primitive-0.7.1.0 (lib)
Starting     vector-0.12.1.2 (lib)
Building     vector-0.12.1.2 (lib)
Installing   vector-0.12.1.2 (lib)
Completed    vector-0.12.1.2 (lib)
Starting     ListLike-4.7.3 (lib)
Building     ListLike-4.7.3 (lib)
Installing   ListLike-4.7.3 (lib)
Completed    ListLike-4.7.3 (lib)
```

**Comment by andreasabel** [comment]
Looks like #10, which is fixed on master.  We should release again.  I'll prepare...

**Comment by asr** [comment]
I'm getting the same error with GHC 9.0.1-rc1 (not a big surprise). The current master (fc051ef219305194422254d36fdcc18de8fb736c) builds with this version of GHC.
 
Blocking https://github.com/agda/agda/issues/4955.

**Comment by andreasabel** [comment]
I'd say 4.7.4 could be released, see successful actions run: https://github.com/ddssff/listlike/actions/runs/465741312.

Both 4.7.3 and 4.7.4 remove some (orphan) instances that have been added as non-orphan instances in the dependencies.  Since our version bounds do not follow §6 the PVP---stating that if we define orphan instances for a data type, we should include the minor version of the defining package into the upper bound---we will likely get similar breakage.  However, if we make the upper bounds stricter, we will likely have to put more labor into relaxing upper bounds.

@ddssff, if you add AndreasAbel to https://hackage.haskell.org/package/ListLike/maintainers/, I can take care of the release.

**Comment by newhoggy** [comment]
I can confirmed that I've used `master` successfully from my `ghc-8.10.3` build.  A release would be most appreciated.

**Comment by ddssff** [comment]
@andreasabel - you are now a ListLike maintainer on hackage.

**Comment by andreasabel** [comment]
Great! I get to work...

**Comment by andreasabel** [comment]
Released 4.7.4: https://hackage.haskell.org/package/ListLike-4.7.4
