### ISSUE TITLE
Doesn't build with dlist 1.0

### ISSUE THREAD

**Issue by felixonmars** [ddssff/listlike#4]
```
[ 6 of 21] Compiling Data.ListLike.DList ( src/Data/ListLike/DList.hs, dist/build/Data/ListLike/DList.dyn_o )

src/Data/ListLike/DList.hs:37:10: error:
    • Couldn't match type ‘[a]’ with ‘DList a’
      Expected type: DList a -> DList a
        Actual type: DList a -> [a]
    • In the expression: D.tail
      In an equation for ‘tail’: tail = D.tail
      In the instance declaration for ‘ListLike (DList a) a’
    • Relevant bindings include
        tail :: DList a -> DList a
          (bound at src/Data/ListLike/DList.hs:37:3)
   |
37 |   tail = D.tail
   |          ^^^^^^
```
